### ISSUE TITLE
WPF Version

### ISSUE THREAD

**Issue by StarNumber12046** [michalleptuch/aurora#1]
Where do I download that?

**Comment by michalleptuch** [comment]
You can download Aurora app from the Store :)

**Comment by StarNumber12046** [comment]
So my ms store doesnt work and as stated in READ,E there is a wpf app. I asked if I could get a download.

**Comment by michalleptuch** [comment]
Yeas, but it's not pure WPF application. It must be downloaded from Microsoft Store app to get an actual license.

**Comment by StarNumber12046** [comment]
oh ok
